// Autogenerated from Pigeon (v16.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class SearchRequest;
@class SearchReply;

@interface SearchRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithQuery:(NSString *)query;
@property(nonatomic, copy) NSString * query;
@end

@interface SearchReply : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithResult:(NSString *)result;
@property(nonatomic, copy) NSString * result;
@end

/// The codec used by Api.
NSObject<FlutterMessageCodec> *ApiGetCodec(void);

@protocol Api
- (void)searchRequest:(SearchRequest *)request completion:(void (^)(SearchReply *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<Api> *_Nullable api);

NS_ASSUME_NONNULL_END
